### ISSUE TITLE
Init

### ISSUE THREAD

**Issue by 4kimov** [sqids/sqids-postgresql#2]
The original Postgres version was written in C: https://github.com/iCyberon/pg_hashids (cc @iCyberon)

@tzvetkoff Any chance that your `sqids-c` could be linked with Postgres to make this one?

**Comment by iCyberon** [comment]
I would be more than happy to migrate.

**Comment by 4kimov** [comment]
Hey @iCyberon, that'd be great! Just sent you a maintainer invite to the repo, so feel free to push as you see fit. I think quite a few people would be happy to see a Postgres version updated (including me).

A bit more on the changes / porting here: https://github.com/sqids/sqids-spec#-how-to-port-sqids-to-another-language

**Comment by JitYc** [comment]
@iCyberon @4kimov 
Big upvote for this, many Supabase users would be thrilled. Any timeline or help needed?

**Comment by 4kimov** [comment]
@JitYc Help would be appreciated, yes.

@iCyberon Looks like you should have access to this repo, do you have an approximate ETA on when you might give this a shot?

**Comment by kryptus36** [comment]
I could *really* use this. Can we put a bounty on it or something?

**Comment by kryptus36** [comment]
For anyone watching this issue, I've implemented a PLPGSQL version at https://github.com/sqids/sqids-plpgsql

Happy to take feedback, PRs, etc.

**Comment by 4kimov** [comment]
Pushed a work-in-progress, works ok in development env. Still missing tests + better error handling. Going to close this general issue, please open new ones as you see specific problems appear.

Of course improvement PRs are welcome.
